from typing import Any, Callable, Literal


def test() -> Literal[1]: ...

JSValue = None | bool | int | float | str | Object

class Object():
    def json(self) -> str: ...
    def __call__(self, *args: Any) -> Any: ...

class Context:
    def eval(self, code: str) -> JSValue: ...
    def module(self, code: str) -> JSValue: ...
    def execute_pending_job(self) -> bool: ...
    def parse_json(self, data: str) -> JSValue: ...
    def get(self, name: str) -> JSValue: ...
    def set(self, name: str, item: JSValue) -> None: ...
    def set_memory_limit(self, limit: int) -> None: ...
    def set_time_limit(self, limit: int) -> None: ...
    def set_max_stack_size(self, limit: int) -> None: ...
    def memory(self) -> dict[str, int]: ...
    def gc(self) -> None: ...
    def add_callable(self, name: str, callable: Callable[..., Any]) -> None: ...
    @property
    def globalThis(self) -> Object: ...

class JSException(Exception):
    pass

class StackOverflow(Exception):
    pass
